### ISSUE TITLE
Thread-safe channels?   Aren't they already thread-safe?  

### ISSUE THREAD

**Issue by cdluv** [enriquebris/goconcurrentqueue#13]
Hi,
It's great that you've implemented a concurrent queue.  It's a very good as an academic exercise, but it's left me slightly confused.

Please can you help me understand what your intent is by sharing your work?  Go has channels, which are effectively concurrent queues that can be safely shared across go-routines.  I'm struggling to understand why you need to put locks around channels. Do you have a test which proves that channels aren't thread-safe?  If so, this sounds like either a bug in Golang, or more likely a bug in either yours or my understanding.  I've been in the game for a long time, and it worries me that this library is an actual thing.  It feels to me like it's putting thread safety around thread safety.

I'd love to hear your thoughts.  I'm always happy to be corrected in my thinking.

**Comment by enriquebris** [comment]
Hi!

Short story: I'm working on a [workers pool golang package](https://github.com/enriquebris/goworkerpool) and realize that some architectural changes were needed to improve the performance. Part  of the changes involve the addition of concurrent queues and my first approach was to use channels (is there any better concurrent queue than a channel? No doubts about it). As the project evolved the queue's handling started adding more noise than expected and that's why I decided to encapsulate all their logic in a separate package. So, this is a wrapper of what could be done using channels.

The goal behind sharing this package is looking to help people in need of a concurrent queue but without the time to deal with little details about the way it could be done by scratch (using channels).

Regarding locks, the idea is to allow blocking the queue (not the channel). While the queue is blocked no elements could be enqueued/dequeued.
